profile_type: nimbus-static
iaas:
  site: ooi.ucsd
  key: mXSkX6oJSG0RIHhEgP0Q8
  secret: 5eaPA6duUVzI859BAb9mdqCy4hwNW0Oq6nFmtuMux9
  url: https://nimbus-dev0.oceanobservatories.org:8444
  # base-image: r2-worker
  base-image: r2-worker-stage
  base-allocation: m1.xlarge
  sshkeyname: ooi
rabbitmq:
  host: r01.dev.oceanobservatories.org
  username: guest
  password: guest
postgres: 
  host: pg.dev.oceanobservatories.org
  password: 003y3C3Y3
  admin_username: ooiuser
  admin_password: 003y3C3Y3
zookeeper:
  hosts: [zk01.dev.oceanobservatories.org, zk02.dev.oceanobservatories.org, zk03.dev.oceanobservatories.org]
  enabled: true
graylog:
  host: logging.dev.oceanobservatories.org

# Package versions
packages:
  coi_services: http://sddevrepo.oceanobservatories.org/releases/coi-services-ooici-REL2.0.tar.gz
# if desired, include a list of hostnames here which will be DDNS-assigned
# to the service gateway VMs. Ensure you have at least as many hostnames
# as there will ever be VMs.
gateway_ddns_hosts:
  - sg01.dev.oceanobservatories.org
  - sg02.dev.oceanobservatories.org
  - sg03.dev.oceanobservatories.org
  - sg04.dev.oceanobservatories.org
pyon_config_output: REPLACE_WITH_PYON_CONFIG
trafficsentinel:                                                                 
  host: trafficsentinel.oceanobservatories.org                                   
  username: developer                                                            
  password: developer8 
