profile_type: nimbus-static
iaas:
  site: ooi.ucsd
  key: E5Pm3LAVqph0qZtWlvQBQ
  secret: RXawkaJQHYB3vhtnf0gIYlx4OjfhQ3kkcK0oRQU4A7 
  url: https://nimbus-dev0.oceanobservatories.org:8444
  base-image: r2-worker-stage
  base-allocation: m1.xlarge
  sshkeyname: ooi
rabbitmq:
  host: rabbit.a3.oceanobservatories.org
  # host: rabbit.a.oceanobservatories.org
  username: guest
  password: guest
postgres: 
  # host: pg.a.oceanobservatories.org
  host: pg.a3.oceanobservatories.org
  password: 003y3C3Y3
  admin_username: ooiuser
  admin_password: 003y3C3Y3
zookeeper:
  hosts: [zk01.a3.oceanobservatories.org, zk02.a3.oceanobservatories.org, zk03.a3.oceanobservatories.org]
  enabled: true
graylog:
  host: logging.a3.oceanobservatories.org

# Package versions
packages:
  coi_services: http://sddevrepo.oceanobservatories.org/releases/coi-services-ooici-master.tar.gz
# if desired, include a list of hostnames here which will be DDNS-assigned
# to the service gateway VMs. Ensure you have at least as many hostnames
# as there will ever be VMs.
gateway_ddns_hosts:
  - sg01.a3.oceanobservatories.org
  - sg02.a3.oceanobservatories.org
  - sg03.a3.oceanobservatories.org
  - sg04.a3.oceanobservatories.org
pyon_config_output: REPLACE_WITH_PYON_CONFIG
