profile_type: nimbus-static
iaas:
  site: ooi.ucsd
  key: Rvp3nHCI03zGRGoOrBO1n
  secret: xj8LRHvNkLsNEeK5zqmS4VAnwDMwdbgqu3hcRwxNcX
  url: https://nimbus-prod.oceanobservatories.org:8444
  base-image: r2-worker
  base-allocation: m1.xlarge
  sshkeyname: ooi
rabbitmq:
  host: r01.b.oceanobservatories.org
  username: ooistagermq
  password: RBT5t2G3
postgres:
  host: pg.b.oceanobservatories.org
  password: 003y3C3Y3
  admin_username: ooiuser
  admin_password: 003y3C3Y3
graylog:
  host: logging.b.oceanobservatories.org
zookeeper:
  hosts: [zk01.b.oceanobservatories.org,zk02.b.oceanobservatories.org,zk03.b.oceanobservatories.org]
  enabled: true

# Package versions
packages:
  coi_services: http://sddevrepo.oceanobservatories.org/releases/coi-services-ooici-REL2.0-REPLACE_WITH_COI_VERS.tar.gz
  dt_data: http://sddevrepo.oceanobservatories.org/releases/dt-data-ooici-REL2.0-REPLACE_WITH_DTDATA_VERS.tar.gz
  epu: http://sddevrepo.oceanobservatories.org/releases/epu-venv-ooici-REL2.0-REPLACE_WITH_EPU_VERS.tar.gz
  epuagent: http://sddevrepo.oceanobservatories.org/releases/epuagent-venv-ooici-REL2.0-REPLACE_WITH_EPUAGENT_VERS.tar.gz

# if desired, include a list of hostnames here which will be DDNS-assigned
# to the service gateway VMs. Ensure you have at least as many hostnames
# as there will ever be VMs.
gateway_ddns_hosts:
  - sg01.b.oceanobservatories.org
  - sg02.b.oceanobservatories.org
  - sg03.b.oceanobservatories.org
  - sg04.b.oceanobservatories.org
  - sg05.b.oceanobservatories.org
  - sg06.b.oceanobservatories.org
  - sg07.b.oceanobservatories.org
  - sg08.b.oceanobservatories.org
  - sg09.b.oceanobservatories.org
  - sg10.b.oceanobservatories.org
  - sg11.b.oceanobservatories.org
  - sg12.b.oceanobservatories.org
  - sg13.b.oceanobservatories.org
  - sg14.b.oceanobservatories.org
  - sg15.b.oceanobservatories.org
  - sg16.b.oceanobservatories.org

pyon_config_output: /var/jenkins/workspace/ION_Beta/coi-services/res/config/pyon.local.yml
