type: launch
name: lightweight
version: 0.2
#############################################################################
# PYON CONFIGURATION
#############################################################################
config:
  processdispatcher:
    restart_throttling_config:
        minimum_time_between_starts: 2

# this configuration block is merged into a base pyon.yml including common
# parameters like RabbitMQ and CouchDB blocks.

#############################################################################
## EXECUTION ENGINES
##############################################################################

execution_engines:
  default:
    base_need: 1
    replicas: 1
    slots: 200

default_execution_engine: default

#############################################################################
#  APPS
#############################################################################

app_defaults:
  ha:
    policy: npreserving
    parameters:
      preserve_n: 1

# apps included below override the app_defaults block. apps present in the REL
# but not below use the app_defaults block
apps:

  # bootstrap processes do not deploy with HA so we override the defaults
  bootstrapper1: {}
  bootstrapper2: {}
  bootstrapper3: {}
  parameter_bootstrap: {}
  policy_bootstrap: {}
  qc_post_processor:
    include: False
  vis_user_queue_monitor:
    include: False
