type: launch
name: nightly
version: 0.2
#############################################################################
# PYON CONFIGURATION
#############################################################################
config:
  container:
    objects:
      validate:
        setattr: False
  endpoint:
    receive:
      timeout: 60
  processdispatcher:
    restart_throttling_config:
        minimum_time_between_starts: 2
  interceptor:
    interceptors:
      validate:
        config:
          enabled: False

# this configuration block is merged into a base pyon.yml including common
# parameters like RabbitMQ and CouchDB blocks.

#############################################################################
## CEI BASE NODE
##############################################################################
basenodes:
  basenode:
    process_dispatcher:
      replicas: 2
    epum:
      replicas: 2
    provisioner:
      replicas: 2


#############################################################################
## EXECUTION ENGINES
##############################################################################

execution_engines:
  default:
    base_need: 1
    replicas: 2
    slots: 100

default_execution_engine: default

#############################################################################
#  APPS
#############################################################################

app_defaults:
  ha:
    policy: npreserving
    parameters:
      preserve_n: 1

# apps included below override the app_defaults block. apps present in the REL
# but not below use the app_defaults block
apps:

  # bootstrap processes do not deploy with HA so we override the defaults
  bootstrapper1: {}
  bootstrapper2: {}
  bootstrapper3: {}
  parameter_bootstrap: {}
  policy_bootstrap: {}
  qc_post_processor:
    include: False
  vis_user_queue_monitor:
    include: False

  visualization_service:
    ha:
      policy: sensor
      parameters:
        metric: "app_attributes:ps"
        minimum_processes: 1
        maximum_processes: 3
        sample_period: 600
        sample_function: Average
        cooldown_period: 60
        scale_up_threshold: 20
        scale_down_n_processes: 1
        scale_down_threshold: 2
        scale_up_n_processes: 1
